### ISSUE TITLE
Data sets are not listed when some of them are archived

### ISSUE THREAD

**Issue by JirkaAichler** [zowe/zowe-explorer-intellij#129]
I am getting the following error message when trying to list data sets that may be archived:

```
Cannot retrieve dataset list Code: 500 CATEGORY: 2.0 MESSAGE: ServletDispatcher failed - received TSO Prompt when expecting TsoServletResponse RETURN CODE: 4.0 DETAILS: DMS2987 DATA SET CATALOGED TO CA DISK PSEUDO-VOLUME ARCIVE DMS2987 CA DISK HAS ARCHIVED USER.DEPLOY.COPY DMS2971 DO YOU WANT TO RESTORE THE DATA SET? (Y/N) REASON: 3.0
```

No data sets are displayed.

**Comment by KUGDev** [comment]
It looks like Zowe Explorer VSCode had similar problem that is already resolved
https://github.com/zowe/vscode-extension-for-zowe/issues/235
Looking into it to introduce compliant changes

**Comment by apurvraj** [comment]
I see that this issue is again emanating from ZOWE REST API side....here is the screenshot where I am running with latest Zowe CLI version 7.12.0.
![image](https://user-images.githubusercontent.com/33894076/229827512-36bd3f42-81ab-4d9f-93d7-4ff0fd611958.png)

The same issue in the latest version (2.7.0) of Zowe Explorer...

![image](https://user-images.githubusercontent.com/33894076/229828572-45d11659-86a3-4dad-80e8-5ce23fce8cfa.png)

**Comment by KUGDev** [comment]
Hello @apurvraj 
Thanks for the investigation
In the thread I've attached, there is an explanation of the issue:
https://github.com/zowe/vscode-extension-for-zowe/issues/235#issuecomment-557158009
For the IntelliJ Plugin, we are investigating the possibility to fix this

**Comment by KUGDev** [comment]
Ready for test: https://plugins.jetbrains.com/plugin/18688-zowe-explorer/versions/preview

**Comment by KUGDev** [comment]
https://github.com/zowe/zowe-explorer-intellij/commit/e125325a
