### ISSUE TITLE
UX: Edit WS mask

### ISSUE THREAD

**Issue by pinpan** [zowe/zowe-explorer-intellij#14]
Mask can be edited only in the Settings dialog when editing a WS. At the same time the mask is not visible there. 
On contrary the mask can’t be edited in the Tool window where it is visible.

**Comment by KUGDev** [comment]
Hi @pinpan 
Could you check the functionality in the latest version of the plugin?

**Comment by pinpan** [comment]
Now I can edit the WS mask. 
Just a minor complaint, after I select "Edit" from the pop-up menu, the dialog title is "Rename Dataset Mask". Maybe "Edit" is more appropriate.

**Comment by pinpan** [comment]
Another minor improvement suggestion: Suggest "*" as a default DS mask value, similar to the Job Working Set mask name.

**Comment by KUGDev** [comment]
Hello @pinpan 
We discussed the issue
Considering "*" as a default DS mask value, it can cause a lot of issues regarding fetch for related datasets list, as it is the operation that can affect a big amount of items. It caused some problems in our system, so we disabled such possibility.
If we are talking about "*" as "USERHQL.*", then we can implement this, for sure.
Regarding the "Edit" instead of "Rename": actually, it is a bug, that will be fixed in the next version. It should show "Rename" both for dialog window and context menu
